### ISSUE TITLE
> Faz sentido sim. Como são 3 opções e considerando próximos passos de compatibilidade com Maven e Gradle, vejo como prioridade a utilização inicialmente com Spring Data, e, realizar incremento com as opções de JDBC Template e JDBC puro.

### ISSUE THREAD

**Issue by wesleyzup** [stack-spot/graphene-java-api-stack#15]
Boa tarde Vitor, 

1. Por favor, replicar a configuração do postgres que você adicionou no **application.yaml** nos arquivos **application-dev.yaml**, **application-hom.yaml** e **application-prod.yaml** para que tenhamos uma pré configuração para todos os ambientes.

**ex:**
  ```yaml
  spring:
    datasource:
      driver-class-name: org.postgresql.Driver
      url: ${JDBC_URL}
      username: ${DB_USERNAME}
      password: ${DB_PASSWORD}
    jpa:
      generate-ddl: true
      show-sql: true
      hibernate:
        ddl-auto: update
      database-platform: org.hibernate.dialect.PostgreSQLDialect
  ```

2. Utilizar o input global **build_tool** para adicionar a dependencia no arquivo de build(gradle or maven), correspondente a aplicação gerada. Com esse atributo você pode utilizar um hook para tomada de decisão, e saber em qual arquivo a dependencia deve ser incluída.

**Segue exemplo:** https://github.com/stack-spot/graphene-java-api-stack/blob/main/metrics-plugin/plugin.yaml

3. Realizar o mesmo processo para o mariadb, para que o fluxo seja atendido caso seja essa a escolha do usuário.
